### ISSUE TITLE
doesn't work with default handler.

### ISSUE THREAD

**Issue by Levenson** [antifuchs/cxml-rpc#1]
http://paste.lisp.org/display/130762#1

Hunchentoot reply object is available now by "hunchentoot:request-method*"

**Comment by antifuchs** [comment]
Thanks for the bug report, and thanks for doing most of the diagnosis work for me already! I'm sorry I didn't get a chance to take a look yet, but will hopefully be able to over the next week or so.

**Comment by antifuchs** [comment]
I just pushed a commit to fix this. (And in the process, found a bug in cxml's char decoding routines on CCL, win all around!) Thanks again!
